sudo: required
before_install:
- sudo dpkg --purge --force-depends ca-certificates-java
- sudo apt-get install -qq ca-certificates-java
- sudo mkdir -p ~/ssl_certs/
- sudo openssl s_client -connect services.gradle.org:443 > ~/ssl_certs/services.gradle.org.pem
- sudo ${JAVA_HOME}/jre/bin/keytool -import -alias services.gradle.org -keypass changeit -keystore ${JAVA_HOME}/jre/lib/security/cacerts -file ~/ssl_certs/services.gradle.org.pem
- sudo openssl s_client -connect plugins.gradle.org:443 > ~/ssl_certs/plugins.gradle.org.pem
- sudo ${JAVA_HOME}/jre/bin/keytool -import -alias plugins.gradle.org -keypass changeit -keystore ${JAVA_HOME}/jre/lib/security/cacerts -file ~/ssl_certs/plugins.gradle.org.pem
- ./gradlew clean
language: java
jdk:
- oraclejdk7
- openjdk6
script: ./gradlew test
