sudo: required
before_install:
- sudo apt-get install --reinstall -qq ca-certificates
- sudo apt-get install --reinstall -qq ca-certificates-java
- sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure
language: java
jdk:
- oraclejdk7
- openjdk6
script: gradle test
