sudo: required
before_install:
- sudo dpkg --purge --force-depends ca-certificates-java
- sudo apt-get install -qq ca-certificates-java
language: java
jdk:
- oraclejdk7
- openjdk6
script: ./gradlew test
